In [134]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression

In [135]:
data = pd.read_csv("../data/1.02. Multiple linear regression.csv")

In [136]:
data

,SAT,GPA,"Rand 1,2,3"
0,1714,2.40,1
1,1664,2.52,3
2,1760,2.54,3
3,1685,2.74,3
4,1693,2.83,2
...,...,...,...
79,1936,3.71,3
80,1810,3.71,1
81,1987,3.73,3
82,1962,3.76,1


In [137]:
data.describe()

,SAT,GPA,"Rand 1,2,3"
count,84.000000,84.000000,84.000000
mean,1845.273810,3.330238,2.059524
std,104.530661,0.271617,0.855192
min,1634.000000,2.400000,1.000000
25%,1772.000000,3.190000,1.000000
50%,1846.000000,3.380000,2.000000
75%,1934.000000,3.502500,3.000000
max,2050.000000,3.810000,3.000000


In [138]:
# 変数を定義する
y = data["GPA"]
x = data[["SAT", "Rand 1,2,3"]]

In [139]:
reg = LinearRegression()
reg.fit(x, y)

LinearRegression()

In [140]:
# 係数, 切片, 決定係数を表示する
(reg.coef_), (reg.intercept_), (reg.score(x, y))

(array([ 0.00165354, -0.00826982]), 0.29603261264909575, 0.4066811952814282)

In [141]:
# 決定係数を計算する
reg.score(x, y)

0.4066811952814282

In [142]:
from sklearn.feature_selection import f_regression

In [143]:
f_regression(x, y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [144]:
reg_summary = pd.DataFrame(data=x.columns.values, columns=["Features"])
reg_summary

,Features
0,SAT
1,"Rand 1,2,3"


In [145]:
# まとめ表を作成する
reg_summary["Coefficients"] = reg.coef_
reg_summary["p-values"] = f_regression(x, y)[1]

In [146]:
reg_summary

,Features,Coefficients,p-values
0,SAT,0.001654,7.199518e-11
1,"Rand 1,2,3",-0.008270,6.762914e-01


In [147]:
# 標準化
from sklearn.preprocessing import StandardScaler

In [148]:
scaler = StandardScaler()
scaler.fit(x)

StandardScaler()

In [149]:
x_scaled = scaler.transform(x)
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [150]:
# 標準化したデータで回帰分析を行う
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [151]:
# 係数, 切片, 決定係数を表示する
reg.coef_, reg.intercept_, reg.score(x_scaled, y)

(array([ 0.17181389, -0.00703007]), 3.330238095238095, 0.4066811952814283)

In [152]:
reg_summary = pd.DataFrame([["Bias"], ["SAT"], ["Rand 1,2,3"]], columns=["Features"])
reg_summary["Weights"] = reg.intercept_, reg.coef_[0], reg.coef_[1]
reg_summary

# 重みが大きいのはSATの方である
# 消してもモデルに影響はない、この重みがあることにより、P値を表示するメソッドがない

,Features,Weights
0,Bias,3.330238
1,SAT,0.171814
2,"Rand 1,2,3",-0.007030


In [153]:
# 予測
new_data = pd.DataFrame(data=[[1700, 2], [1800, 1]], columns=["SAT", "Rand 1,2,3"])
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-0.43571643, -1.24637147]])

In [154]:
reg.predict(new_data_scaled)

array([3.09051403, 3.26413803])